sudo: false
language: python
python: '3.6'


install:
  - pip install tox

script:
  - tox

branches:
    only:
    - master
    - dev

notifications:
    email:
     recipients:
     - python@michelfe.it
     on_success: never
     on_failure: always
     on_start: never   # options: [always|never|change] default: always
